### ISSUE TITLE
ASIFT SRS

### ISSUE THREAD

**Issue by iparask** [iceberg-project/ICEBERG-administration#5]
The sections such as `operating environment` is missing. @AymenFJA can you please add the necessary information there?

Also if you feel that something is missing in the document and you can add it, feel free to do so.

**Comment by AymenFJA** [comment]
Hey @iparask  , i will start filling some of the information that I know about the ASIFT use case.

 thanks.

**Comment by iparask** [comment]
This issue is a duplicate of #11. Closing
